services:
  postgres:
    image: 'postgres:17-alpine'
    env_file:
      - .env
    volumes:
      - ./Backend/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    image: eclipse-temurin:25-jdk-alpine
    platform: linux/amd64
    container_name: anteiku-backend
    working_dir: /app
    volumes:
      - ./Backend:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres
      - logstash
    env_file:
      - .env
    environment:
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    command: ./mvnw clean spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  frontend:
    build: 
      context: ./Frontend/app_react
      dockerfile: ../Dockerfile
    container_name: anteiku-frontend
    volumes:
      - ./Frontend/app_react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.1
    container_name: anteiku-elasticsearch
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - default

  logstash:
    image: docker.elastic.co/logstash/logstash:9.3.1
    container_name: anteiku-logstash
    env_file:
      - .env
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "50000:50000"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    depends_on:
      - elasticsearch
    networks:
      - default

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.1
    container_name: anteiku-kibana
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - default

volumes:
  db_data:
  es_data: