consumer:
  topic: "user-notifs"
  brokers: "kafka:29092"
  user_notifications_database_addr: "cassandra:9042"
  notification_preferences_database_addr: "cassandra:9042"
  clients_node_addr: "0.0.0.0:6969"